update renovate config to add labels and add renovate.json validator
acorn-io/acorn pull request #1333
Opened 2023-03-13 17:15 UTC by jacobdonenfeld

### Checklist
- [ ] The title of this PR would make a good line in Acorn's Release Note's Changelog
- [ ] The title of this PR ends with a link to the main issue being address in paranthesis, like: `This is a title (#1216)`. [Here's an example](https://github.com/acorn-io/acorn/pull/1199)
- [ ] All relevant issues are referenced in the PR description. *NOTE: don't use [GitHub keyworkds](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) that auto-close issues*
- [ ] Commits follow [contributing guidance](https://github.com/acorn-io/acorn/blob/main/CONTRIBUTING.md#commits)
- [ ] Automated tests added to cover the changes. If tests couldn't be added, an explanation is provided in the Verification and Testing section
- [ ] Changes to user-facing functionality, API, CLI, and upgrade impacts are clearly called out in PR description
- [ ] PR has at least two approvals before merging (or a reasonable exception, like it's just a docs change)

2023-03-13 21:37 UTC, thedadams commented
@jacobdonenfeld Can you add a note describing why these changes are necessary?

2023-03-15 21:17 UTC, tylerslaton requested changes
Thanks for the updated description! Couple of comments.

2023-03-15 21:17 UTC, tylerslaton commented on .github/workflows/validate-renovate.yml
> +      - 'master'
This should be `main`, right?
```suggestion
      - 'main'
```

2023-03-15 21:17 UTC, tylerslaton commented on .github/workflows/validate-renovate.yml
> +      - 'env/renovate.json'
Should this be `.github/rennovate.json`? I'm not understanding why it changes here.
```suggestion
      - '.github/renovate.json'
```

2023-03-16 16:39 UTC, tylerslaton approved these changes

2023-03-16 19:01 UTC, thedadams approved these changes

2023-03-18 18:42 UTC, merged