change: generate random suffices for check objects
acorn-io/acorn pull request #671
Opened 2022-09-08 19:50 UTC by iwilltry42

Ref: #644

2022-09-09 13:18 UTC, cjellick approved these changes

2022-09-09 13:20 UTC, cjellick requested changes
Could you just use the GenerateName field instead of the Name field and let k8s make the random name for you?

2022-09-10 09:42 UTC, iwilltry42 commented
> Could you just use the GenerateName field instead of the Name field and let k8s make the random name for you?

For the exec check yes, but in the ingress-check, I have to use name references, so I have to have it available before creating the other objects. I could do that, but that would require the logic to first fetch the first object from the API and retrieve its name.
Doing it based on labels would yield the same "challenge".

2022-09-12 16:45 UTC, cjellick approved these changes

2022-09-12 16:46 UTC, merged

2022-09-27 18:28 UTC, meldafrawi commented
Validation: **PASS**

`acorn check` will create a pod with unique suffix with every run

Running `acorn check`  (x4)

```
kubectl get pod -n acorn-system 
NAME                                READY   STATUS        RESTARTS       AGE
buildkitd-68cdbf6979-rpdfk          2/2     Running       4 (100m ago)   21h
acorn-api-59fb7c754d-mbj9k          1/1     Running       3 (100m ago)   21h
acorn-controller-556fdd9bf9-d568k   1/1     Running       3 (100m ago)   21h
acorn-check-exec-78ztp4k4           1/1     Terminating   0              9s
acorn-check-exec-zc5tkrlg           1/1     Terminating   0              7s
acorn-check-exec-22vl6wlr           1/1     Terminating   0              5s
acorn-check-exec-jbbnm6d8           1/1     Terminating   0              3s

```